/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.gradlew;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
        System.out.println();
        System.out.println("JAVA:", System.getProperty("java.version"));
        System.out.println();
        assertTrue(System.getProperty("java.version"), "18");
    }
}
